# Generated by Django 4.1.6 on 2023-02-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_blueprint', '0003_alter_question_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
