# Generated by Django 4.1.6 on 2023-02-19 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_blueprint', '0007_alter_answer_content_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_vote', to='question_blueprint.answer'),
        ),
    ]
