# Generated by Django 4.1.7 on 2023-04-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_link',
        ),
    ]
