# Generated by Django 4.1.7 on 2023-04-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upvote_num',
            field=models.IntegerField(default=0),
        ),
    ]
