# Generated by Django 4.1.7 on 2023-04-13 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_questionupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
