# Generated by Django 4.1.7 on 2023-05-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_questionupvote_user_answerupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
